### ISSUE TITLE
How to change the 'body' and 'heading' fonts?

### ISSUE THREAD

**Issue by alex-hsa** [forumone/gesso-uswds#117]
Hi:

I changed the fallback fonts in the 'config.design-tokens.yml' file to my custom font names, but unfortunately, the new fonts don't get applied.

### Before:
```   
typography:
    font-family:
      body:
        name: Body
        stack: !sass
          sass: 'font-family(body)'
          fallback: '"Source Sans Pro Web", "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif'
      heading:
        name: Heading
        stack: !sass
          sass: 'font-family(heading)'
          fallback: '"Merriweather Web", Georgia, Cambria, "Times New Roman", Times, serif'
```

### After:
```  
typography:
    font-family:
      body:
        name: Body
        stack: !sass
          sass: 'font-family(body)'
          fallback: 'Montserrat, Arial, sans-serif'
      heading:
        name: Heading
        stack: !sass
          sass: 'font-family(heading)'
          fallback: 'ProdigySansRegular, Arial, sans-serif' 
```

Is there something else that needs to be changed to customize fonts for GUS?
Any pointers would be very much appreciated.

Thank you so much,
Alex

**Comment by coreylafferty** [comment]
The simple way to do this is to just bypass the USWDS font family and declare the stack directly.  For example:

```
typography:
    font-family:
      body:
        name: Body
        stack: 'Montserrat, Arial, sans-serif'
      heading:
        name: Heading
        stack: 'ProdigySansRegular, Arial, sans-serif' 
```

The above is probably what you want, but if you wanted to keep things tied to the USWDS, you can technically create new USWDS font family tokens and redefine what the serif or sans font stacks are for the USWDS.  You'd do that by adding a new family token at the top of styles.scss.  So something like this (I guessed at the cap-height value for Prodigy -- you'd probably need to measure that in Sketch per the instructions in the USWDS stylesheet linked at the end of this comment):

```
$theme-typeface-tokens: (
  prodigy: (
    display-name: 'ProdigySansRegular',
    cap-height: 364px,
  ),
);
```

And then at the top of config.design-tokens.yml, add these new properties to the end of the `uswds` variable to redefine what the serif font and its fallback families are.

```
#font-type-serif: prodigy
#font-serif-custom-stack: Arial, sans-serif
```

That would effectively change the stack for the serif font in the USWDS to be `ProdigySansRegular, Arial, sans-serif`, which would then change what the heading font is (since its defined by the serif font).  

More details here in the USWDS typography stylesheet: https://github.com/uswds/uswds/blob/develop/src/stylesheets/theme/_uswds-theme-typography.scss
